[package]
name = "srisum"
version = "1.0.0"
description = "Compute and check subresource integrity digests"
license-file = "LICENSE"
authors = ["Kat Marchán <kzm@zkat.tech>"]
repository = "https://github.com/zkat/srisum-rs"
homepage = "https://github.com/zkat/srisum-rs"
edition = "2018"

[dependencies]
ssri = "1.3.0"
clap = "2.33.0"
failure = "0.1.5"
